name: CI

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run lint checks
        run: npm run lint

      - name: Run build
        env:
          DEMO_AUDIO_BASE_URL: ${{ secrets.DEMO_AUDIO_BASE_URL }}
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
